### ISSUE TITLE
Problema en despliegue de Catálogo de Procedimientos y Trámitación de Expedientes

### ISSUE THREAD

**Issue by jakinho** [Cenatic/alsigm#18]
Estamos teniendo problemas con los módulos de ‘Catálogo de procedimientos’ y con ‘Tramitador de expedientes’. Se generan los wars correspondientes sin ningún tipo de problema, pero a la hora de desplegar obtenemos los siguientes errores para los mismos:

•	(Catálogo)

```
java.lang.reflect.InvocationTargetException
	at org.apache.commons.digester.Digester.createSAXException(Digester.java:2792)
	at org.apache.commons.digester.Digester.createSAXException(Digester.java:2818)
	at org.apache.commons.digester.Digester.endElement(Digester.java:1070)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.commons.digester.Digester.parse(Digester.java:1591)
	at net.sf.navigator.menu.MenuRepository.load(MenuRepository.java:202)
	at net.sf.navigator.menu.MenuPlugIn.init(MenuPlugIn.java:58)
	at org.apache.struts.action.ActionServlet.initModulePlugIns(ActionServlet.java:839)
	at org.apache.struts.action.ActionServlet.init(ActionServlet.java:332)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at ieci.tdw.ispac.ispacweb.servlet.ISPACActionServlet.init(ISPACActionServlet.java:28)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1284)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1197)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1087)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5266)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5554)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.commons.beanutils.MethodUtils.invokeMethod(MethodUtils.java:216)
	at org.apache.commons.digester.SetNextRule.end(SetNextRule.java:208)
	at org.apache.commons.digester.Rule.end(Rule.java:228)
	at org.apache.commons.digester.Digester.endElement(Digester.java:1067)
	... 30 more
Caused by: java.lang.NoSuchFieldError: log
	at org.apache.velocity.tools.view.servlet.WebappLoader.init(WebappLoader.java:39)
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.initialize(ResourceManagerImpl.java:144)
	at org.apache.velocity.runtime.RuntimeInstance.initializeResourceManager(RuntimeInstance.java:522)
	at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:227)
	at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:461)
	at org.apache.velocity.app.VelocityEngine.init(VelocityEngine.java:106)
	at net.sf.navigator.displayer.VelocityMenuDisplayer.initialize(VelocityMenuDisplayer.java:71)
	at net.sf.navigator.menu.MenuRepository.addMenuDisplayerMapping(MenuRepository.java:168)
	... 38 more
11-jun-2015 12:42:58 org.apache.catalina.core.StandardContext loadOnStartup
GRAVE: Servlet [action] in web application [/SIGEM_CatalogoProcedimientosWeb] threw load() exception
javax.servlet.ServletException: Failure initializing struts-menu: Error parsing resource file: /WEB-INF/menu-config.xml nested exception is: Error at (20, 75: null
	at net.sf.navigator.menu.MenuPlugIn.init(MenuPlugIn.java:65)
	at org.apache.struts.action.ActionServlet.initModulePlugIns(ActionServlet.java:839)
	at org.apache.struts.action.ActionServlet.init(ActionServlet.java:332)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at ieci.tdw.ispac.ispacweb.servlet.ISPACActionServlet.init(ISPACActionServlet.java:28)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1284)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1197)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1087)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5266)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5554)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
11-jun-2015 12:43:01 org.apache.catalina.startup.TaglibUriRule body
```

•	(Tramitador)

```
log4j:WARN Please initialize the log4j system properly.
11-jun-2015 11:56:14 org.apache.catalina.core.ApplicationContext log
GRAVE: action: null
java.lang.NullPointerException
	at ieci.tdw.ispac.ispaclib.util.FileManager.<init>(FileManager.java:30)
	at ieci.tdw.ispac.ispaclib.util.FileTemplateManager.<init>(FileTemplateManager.java:31)
	at ieci.tdw.ispac.ispaclib.util.FileTemplateManager.getInstance(FileTemplateManager.java:25)
	at ieci.tdw.ispac.ispacmgr.common.InitAppPlugin.init(InitAppPlugin.java:37)
	at org.apache.struts.action.ActionServlet.initModulePlugIns(ActionServlet.java:839)
	at org.apache.struts.action.ActionServlet.init(ActionServlet.java:332)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at ieci.tdw.ispac.ispacweb.servlet.ISPACActionServlet.init(ISPACActionServlet.java:28)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1284)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1197)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1087)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5266)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5554)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
11-jun-2015 11:56:14 org.apache.catalina.core.ApplicationContext log
INFO: Marcando el servlet action como no disponible
11-jun-2015 11:56:14 org.apache.catalina.core.StandardContext loadOnStartup
GRAVE: Servlet [action] in web application [/SIGEM_TramitacionWeb] threw load() exception
javax.servlet.UnavailableException
	at org.apache.struts.action.ActionServlet.initModulePlugIns(ActionServlet.java:850)
	at org.apache.struts.action.ActionServlet.init(ActionServlet.java:332)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at ieci.tdw.ispac.ispacweb.servlet.ISPACActionServlet.init(ISPACActionServlet.java:28)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1284)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1197)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1087)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5266)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5554)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
11-jun-2015 11:56:15 org.apache.catalina.startup.TaglibUriRule body
```

El proceso que hemos seguido es:

1 Clonar el branch ‘Development’
2 Ejecutar la siguiente secuencia para la generación de los paquetes:

```
echo  Generacion de Applets
cd framework-filesystem-applet
call mvn clean install -Dmaven.test.skip=true
cd ..
cd framework-scan-applet
call mvn clean install -Dmaven.test.skip=true
cd ..
cd framework-sendFiles-applet
call mvn clean install -Dmaven.test.skip=true
cd ..

echo  Generacion de Framework
cd framework
call mvn clean install -Dmaven.test.skip=true -Pgenerate-jars
cd ..

echo  Generacion de TIME
cd framework-time
call mvn clean install -Dmaven.test.skip=true
cd ..

echo  Generacion de DM
cd framework-dm
call mvn clean install -Dmaven.test.skip=true
cd ..

echo  Generacion de Audit
cd framework-audit
call mvn clean install -Dmaven.test.skip=true
cd ..

echo  Generacion de DIR3
cd framework-dir3
call mvn clean install -Dmaven.test.skip=true
cd ..

echo  Generacion de SIR
cd framework-sir
call mvn clean install -Dmaven.test.skip=true
cd ..

echo  Generacion de CSV
cd framework-csv
call mvn clean install -Dmaven.test.skip=true
cd ..

echo  Generacion de ISICRES
cd registro
call mvn clean install -Dmaven.test.skip=true -Pgenerate-jars -Pgenerate-wars
cd ..

echo  Generacion de Archidoc
cd archivo
call mvn clean install -Dmaven.test.skip=true -Pgenerate-jars -Pgenerate-wars
cd ..

echo  Generacion de Invesflow
cd tramitador
call mvn clean install -Dmaven.test.skip=true  -Pgenerate-jars -Pgenerate-wars
cd ..

echo  Generacion de SIGEM3
cd sigem
call mvn install -Dmaven.test.skip=true -Pgenerate-jars
call mvn clean install -Pgenerate-wars -Dmaven.test.skip=true
```

3 Desplegar los paquetes en tomcat.

Solamente tenemos problemas en un primer momento con esos wars, por ejemplo con Registro podemos trabajar sin problemas. Nos gustaría saber si es algún problema de la rama que hemos escogido como punto de partida o si estamos cometiendo algún error u omitiendo algún paso en la generación de los desplegables que provoque este error.

**Comment by jormaral** [comment]
Probad de nuevo ahora, se han aplicado mejoras a la rama.
